/**
 * Minecraft Bedrock Edition → Java Edition ブロック変換マッピング Part 5
 *
 * 収録カテゴリ:
 *   1. 彩釉テラコッタ (Glazed Terracotta) × 16色 × 4方向
 *   2. シュルカーボックス (Shulker Box) × 16色 + 無色 × 6方向
 *   3. ベッド (Bed) × 16色 × 方向/パーツ
 *
 * 参照: GeyserMC/Geyser mappings/blocks.json
 */

export const BE_TO_JE_BLOCK_MAP_PART5 = {

  // ============================================================
  // SECTION 1: 彩釉テラコッタ (Glazed Terracotta)
  // facing_direction: 0→south, 1→north, 2→north, 3→south, 4→west, 5→east
  // ============================================================

  "minecraft:white_glazed_terracotta": [
    { "bedrock_states": { "facing_direction": 0 }, "java_id": "minecraft:white_glazed_terracotta", "java_states": { "facing": "south" } },
    { "bedrock_states": { "facing_direction": 1 }, "java_id": "minecraft:white_glazed_terracotta", "java_states": { "facing": "north" } },
    { "bedrock_states": { "facing_direction": 2 }, "java_id": "minecraft:white_glazed_terracotta", "java_states": { "facing": "north" } },
    { "bedrock_states": { "facing_direction": 3 }, "java_id": "minecraft:white_glazed_terracotta", "java_states": { "facing": "south" } },
    { "bedrock_states": { "facing_direction": 4 }, "java_id": "minecraft:white_glazed_terracotta", "java_states": { "facing": "west" } },
    { "bedrock_states": { "facing_direction": 5 }, "java_id": "minecraft:white_glazed_terracotta", "java_states": { "facing": "east" } },
  ],

  "minecraft:orange_glazed_terracotta": [
    { "bedrock_states": { "facing_direction": 0 }, "java_id": "minecraft:orange_glazed_terracotta", "java_states": { "facing": "south" } },
    { "bedrock_states": { "facing_direction": 1 }, "java_id": "minecraft:orange_glazed_terracotta", "java_states": { "facing": "north" } },
    { "bedrock_states": { "facing_direction": 2 }, "java_id": "minecraft:orange_glazed_terracotta", "java_states": { "facing": "north" } },
    { "bedrock_states": { "facing_direction": 3 }, "java_id": "minecraft:orange_glazed_terracotta", "java_states": { "facing": "south" } },
    { "bedrock_states": { "facing_direction": 4 }, "java_id": "minecraft:orange_glazed_terracotta", "java_states": { "facing": "west" } },
    { "bedrock_states": { "facing_direction": 5 }, "java_id": "minecraft:orange_glazed_terracotta", "java_states": { "facing": "east" } },
  ],

  "minecraft:magenta_glazed_terracotta": [
    { "bedrock_states": { "facing_direction": 0 }, "java_id": "minecraft:magenta_glazed_terracotta", "java_states": { "facing": "south" } },
    { "bedrock_states": { "facing_direction": 1 }, "java_id": "minecraft:magenta_glazed_terracotta", "java_states": { "facing": "north" } },
    { "bedrock_states": { "facing_direction": 2 }, "java_id": "minecraft:magenta_glazed_terracotta", "java_states": { "facing": "north" } },
    { "bedrock_states": { "facing_direction": 3 }, "java_id": "minecraft:magenta_glazed_terracotta", "java_states": { "facing": "south" } },
    { "bedrock_states": { "facing_direction": 4 }, "java_id": "minecraft:magenta_glazed_terracotta", "java_states": { "facing": "west" } },
    { "bedrock_states": { "facing_direction": 5 }, "java_id": "minecraft:magenta_glazed_terracotta", "java_states": { "facing": "east" } },
  ],

  "minecraft:light_blue_glazed_terracotta": [
    { "bedrock_states": { "facing_direction": 0 }, "java_id": "minecraft:light_blue_glazed_terracotta", "java_states": { "facing": "south" } },
    { "bedrock_states": { "facing_direction": 1 }, "java_id": "minecraft:light_blue_glazed_terracotta", "java_states": { "facing": "north" } },
    { "bedrock_states": { "facing_direction": 2 }, "java_id": "minecraft:light_blue_glazed_terracotta", "java_states": { "facing": "north" } },
    { "bedrock_states": { "facing_direction": 3 }, "java_id": "minecraft:light_blue_glazed_terracotta", "java_states": { "facing": "south" } },
    { "bedrock_states": { "facing_direction": 4 }, "java_id": "minecraft:light_blue_glazed_terracotta", "java_states": { "facing": "west" } },
    { "bedrock_states": { "facing_direction": 5 }, "java_id": "minecraft:light_blue_glazed_terracotta", "java_states": { "facing": "east" } },
  ],

  "minecraft:yellow_glazed_terracotta": [
    { "bedrock_states": { "facing_direction": 0 }, "java_id": "minecraft:yellow_glazed_terracotta", "java_states": { "facing": "south" } },
    { "bedrock_states": { "facing_direction": 1 }, "java_id": "minecraft:yellow_glazed_terracotta", "java_states": { "facing": "north" } },
    { "bedrock_states": { "facing_direction": 2 }, "java_id": "minecraft:yellow_glazed_terracotta", "java_states": { "facing": "north" } },
    { "bedrock_states": { "facing_direction": 3 }, "java_id": "minecraft:yellow_glazed_terracotta", "java_states": { "facing": "south" } },
    { "bedrock_states": { "facing_direction": 4 }, "java_id": "minecraft:yellow_glazed_terracotta", "java_states": { "facing": "west" } },
    { "bedrock_states": { "facing_direction": 5 }, "java_id": "minecraft:yellow_glazed_terracotta", "java_states": { "facing": "east" } },
  ],

  "minecraft:lime_glazed_terracotta": [
    { "bedrock_states": { "facing_direction": 0 }, "java_id": "minecraft:lime_glazed_terracotta", "java_states": { "facing": "south" } },
    { "bedrock_states": { "facing_direction": 1 }, "java_id": "minecraft:lime_glazed_terracotta", "java_states": { "facing": "north" } },
    { "bedrock_states": { "facing_direction": 2 }, "java_id": "minecraft:lime_glazed_terracotta", "java_states": { "facing": "north" } },
    { "bedrock_states": { "facing_direction": 3 }, "java_id": "minecraft:lime_glazed_terracotta", "java_states": { "facing": "south" } },
    { "bedrock_states": { "facing_direction": 4 }, "java_id": "minecraft:lime_glazed_terracotta", "java_states": { "facing": "west" } },
    { "bedrock_states": { "facing_direction": 5 }, "java_id": "minecraft:lime_glazed_terracotta", "java_states": { "facing": "east" } },
  ],

  "minecraft:pink_glazed_terracotta": [
    { "bedrock_states": { "facing_direction": 0 }, "java_id": "minecraft:pink_glazed_terracotta", "java_states": { "facing": "south" } },
    { "bedrock_states": { "facing_direction": 1 }, "java_id": "minecraft:pink_glazed_terracotta", "java_states": { "facing": "north" } },
    { "bedrock_states": { "facing_direction": 2 }, "java_id": "minecraft:pink_glazed_terracotta", "java_states": { "facing": "north" } },
    { "bedrock_states": { "facing_direction": 3 }, "java_id": "minecraft:pink_glazed_terracotta", "java_states": { "facing": "south" } },
    { "bedrock_states": { "facing_direction": 4 }, "java_id": "minecraft:pink_glazed_terracotta", "java_states": { "facing": "west" } },
    { "bedrock_states": { "facing_direction": 5 }, "java_id": "minecraft:pink_glazed_terracotta", "java_states": { "facing": "east" } },
  ],

  "minecraft:gray_glazed_terracotta": [
    { "bedrock_states": { "facing_direction": 0 }, "java_id": "minecraft:gray_glazed_terracotta", "java_states": { "facing": "south" } },
    { "bedrock_states": { "facing_direction": 1 }, "java_id": "minecraft:gray_glazed_terracotta", "java_states": { "facing": "north" } },
    { "bedrock_states": { "facing_direction": 2 }, "java_id": "minecraft:gray_glazed_terracotta", "java_states": { "facing": "north" } },
    { "bedrock_states": { "facing_direction": 3 }, "java_id": "minecraft:gray_glazed_terracotta", "java_states": { "facing": "south" } },
    { "bedrock_states": { "facing_direction": 4 }, "java_id": "minecraft:gray_glazed_terracotta", "java_states": { "facing": "west" } },
    { "bedrock_states": { "facing_direction": 5 }, "java_id": "minecraft:gray_glazed_terracotta", "java_states": { "facing": "east" } },
  ],

  // BE: silver_glazed_terracotta → JE: light_gray_glazed_terracotta
  "minecraft:silver_glazed_terracotta": [
    { "bedrock_states": { "facing_direction": 0 }, "java_id": "minecraft:light_gray_glazed_terracotta", "java_states": { "facing": "south" } },
    { "bedrock_states": { "facing_direction": 1 }, "java_id": "minecraft:light_gray_glazed_terracotta", "java_states": { "facing": "north" } },
    { "bedrock_states": { "facing_direction": 2 }, "java_id": "minecraft:light_gray_glazed_terracotta", "java_states": { "facing": "north" } },
    { "bedrock_states": { "facing_direction": 3 }, "java_id": "minecraft:light_gray_glazed_terracotta", "java_states": { "facing": "south" } },
    { "bedrock_states": { "facing_direction": 4 }, "java_id": "minecraft:light_gray_glazed_terracotta", "java_states": { "facing": "west" } },
    { "bedrock_states": { "facing_direction": 5 }, "java_id": "minecraft:light_gray_glazed_terracotta", "java_states": { "facing": "east" } },
  ],

  "minecraft:cyan_glazed_terracotta": [
    { "bedrock_states": { "facing_direction": 0 }, "java_id": "minecraft:cyan_glazed_terracotta", "java_states": { "facing": "south" } },
    { "bedrock_states": { "facing_direction": 1 }, "java_id": "minecraft:cyan_glazed_terracotta", "java_states": { "facing": "north" } },
    { "bedrock_states": { "facing_direction": 2 }, "java_id": "minecraft:cyan_glazed_terracotta", "java_states": { "facing": "north" } },
    { "bedrock_states": { "facing_direction": 3 }, "java_id": "minecraft:cyan_glazed_terracotta", "java_states": { "facing": "south" } },
    { "bedrock_states": { "facing_direction": 4 }, "java_id": "minecraft:cyan_glazed_terracotta", "java_states": { "facing": "west" } },
    { "bedrock_states": { "facing_direction": 5 }, "java_id": "minecraft:cyan_glazed_terracotta", "java_states": { "facing": "east" } },
  ],

  "minecraft:purple_glazed_terracotta": [
    { "bedrock_states": { "facing_direction": 0 }, "java_id": "minecraft:purple_glazed_terracotta", "java_states": { "facing": "south" } },
    { "bedrock_states": { "facing_direction": 1 }, "java_id": "minecraft:purple_glazed_terracotta", "java_states": { "facing": "north" } },
    { "bedrock_states": { "facing_direction": 2 }, "java_id": "minecraft:purple_glazed_terracotta", "java_states": { "facing": "north" } },
    { "bedrock_states": { "facing_direction": 3 }, "java_id": "minecraft:purple_glazed_terracotta", "java_states": { "facing": "south" } },
    { "bedrock_states": { "facing_direction": 4 }, "java_id": "minecraft:purple_glazed_terracotta", "java_states": { "facing": "west" } },
    { "bedrock_states": { "facing_direction": 5 }, "java_id": "minecraft:purple_glazed_terracotta", "java_states": { "facing": "east" } },
  ],

  "minecraft:blue_glazed_terracotta": [
    { "bedrock_states": { "facing_direction": 0 }, "java_id": "minecraft:blue_glazed_terracotta", "java_states": { "facing": "south" } },
    { "bedrock_states": { "facing_direction": 1 }, "java_id": "minecraft:blue_glazed_terracotta", "java_states": { "facing": "north" } },
    { "bedrock_states": { "facing_direction": 2 }, "java_id": "minecraft:blue_glazed_terracotta", "java_states": { "facing": "north" } },
    { "bedrock_states": { "facing_direction": 3 }, "java_id": "minecraft:blue_glazed_terracotta", "java_states": { "facing": "south" } },
    { "bedrock_states": { "facing_direction": 4 }, "java_id": "minecraft:blue_glazed_terracotta", "java_states": { "facing": "west" } },
    { "bedrock_states": { "facing_direction": 5 }, "java_id": "minecraft:blue_glazed_terracotta", "java_states": { "facing": "east" } },
  ],

  "minecraft:brown_glazed_terracotta": [
    { "bedrock_states": { "facing_direction": 0 }, "java_id": "minecraft:brown_glazed_terracotta", "java_states": { "facing": "south" } },
    { "bedrock_states": { "facing_direction": 1 }, "java_id": "minecraft:brown_glazed_terracotta", "java_states": { "facing": "north" } },
    { "bedrock_states": { "facing_direction": 2 }, "java_id": "minecraft:brown_glazed_terracotta", "java_states": { "facing": "north" } },
    { "bedrock_states": { "facing_direction": 3 }, "java_id": "minecraft:brown_glazed_terracotta", "java_states": { "facing": "south" } },
    { "bedrock_states": { "facing_direction": 4 }, "java_id": "minecraft:brown_glazed_terracotta", "java_states": { "facing": "west" } },
    { "bedrock_states": { "facing_direction": 5 }, "java_id": "minecraft:brown_glazed_terracotta", "java_states": { "facing": "east" } },
  ],

  "minecraft:green_glazed_terracotta": [
    { "bedrock_states": { "facing_direction": 0 }, "java_id": "minecraft:green_glazed_terracotta", "java_states": { "facing": "south" } },
    { "bedrock_states": { "facing_direction": 1 }, "java_id": "minecraft:green_glazed_terracotta", "java_states": { "facing": "north" } },
    { "bedrock_states": { "facing_direction": 2 }, "java_id": "minecraft:green_glazed_terracotta", "java_states": { "facing": "north" } },
    { "bedrock_states": { "facing_direction": 3 }, "java_id": "minecraft:green_glazed_terracotta", "java_states": { "facing": "south" } },
    { "bedrock_states": { "facing_direction": 4 }, "java_id": "minecraft:green_glazed_terracotta", "java_states": { "facing": "west" } },
    { "bedrock_states": { "facing_direction": 5 }, "java_id": "minecraft:green_glazed_terracotta", "java_states": { "facing": "east" } },
  ],

  "minecraft:red_glazed_terracotta": [
    { "bedrock_states": { "facing_direction": 0 }, "java_id": "minecraft:red_glazed_terracotta", "java_states": { "facing": "south" } },
    { "bedrock_states": { "facing_direction": 1 }, "java_id": "minecraft:red_glazed_terracotta", "java_states": { "facing": "north" } },
    { "bedrock_states": { "facing_direction": 2 }, "java_id": "minecraft:red_glazed_terracotta", "java_states": { "facing": "north" } },
    { "bedrock_states": { "facing_direction": 3 }, "java_id": "minecraft:red_glazed_terracotta", "java_states": { "facing": "south" } },
    { "bedrock_states": { "facing_direction": 4 }, "java_id": "minecraft:red_glazed_terracotta", "java_states": { "facing": "west" } },
    { "bedrock_states": { "facing_direction": 5 }, "java_id": "minecraft:red_glazed_terracotta", "java_states": { "facing": "east" } },
  ],

  "minecraft:black_glazed_terracotta": [
    { "bedrock_states": { "facing_direction": 0 }, "java_id": "minecraft:black_glazed_terracotta", "java_states": { "facing": "south" } },
    { "bedrock_states": { "facing_direction": 1 }, "java_id": "minecraft:black_glazed_terracotta", "java_states": { "facing": "north" } },
    { "bedrock_states": { "facing_direction": 2 }, "java_id": "minecraft:black_glazed_terracotta", "java_states": { "facing": "north" } },
    { "bedrock_states": { "facing_direction": 3 }, "java_id": "minecraft:black_glazed_terracotta", "java_states": { "facing": "south" } },
    { "bedrock_states": { "facing_direction": 4 }, "java_id": "minecraft:black_glazed_terracotta", "java_states": { "facing": "west" } },
    { "bedrock_states": { "facing_direction": 5 }, "java_id": "minecraft:black_glazed_terracotta", "java_states": { "facing": "east" } },
  ],

  // ============================================================
  // SECTION 2: シュルカーボックス (Shulker Box)
  // facing_direction: 0=down, 1=up, 2=north, 3=south, 4=west, 5=east
  // ============================================================

  "minecraft:shulker_box": [
    // white
    { "bedrock_states": { "color": "white", "facing_direction": 0 }, "java_id": "minecraft:white_shulker_box", "java_states": { "facing": "down" } },
    { "bedrock_states": { "color": "white", "facing_direction": 1 }, "java_id": "minecraft:white_shulker_box", "java_states": { "facing": "up" } },
    { "bedrock_states": { "color": "white", "facing_direction": 2 }, "java_id": "minecraft:white_shulker_box", "java_states": { "facing": "north" } },
    { "bedrock_states": { "color": "white", "facing_direction": 3 }, "java_id": "minecraft:white_shulker_box", "java_states": { "facing": "south" } },
    { "bedrock_states": { "color": "white", "facing_direction": 4 }, "java_id": "minecraft:white_shulker_box", "java_states": { "facing": "west" } },
    { "bedrock_states": { "color": "white", "facing_direction": 5 }, "java_id": "minecraft:white_shulker_box", "java_states": { "facing": "east" } },
    // orange
    { "bedrock_states": { "color": "orange", "facing_direction": 0 }, "java_id": "minecraft:orange_shulker_box", "java_states": { "facing": "down" } },
    { "bedrock_states": { "color": "orange", "facing_direction": 1 }, "java_id": "minecraft:orange_shulker_box", "java_states": { "facing": "up" } },
    { "bedrock_states": { "color": "orange", "facing_direction": 2 }, "java_id": "minecraft:orange_shulker_box", "java_states": { "facing": "north" } },
    { "bedrock_states": { "color": "orange", "facing_direction": 3 }, "java_id": "minecraft:orange_shulker_box", "java_states": { "facing": "south" } },
    { "bedrock_states": { "color": "orange", "facing_direction": 4 }, "java_id": "minecraft:orange_shulker_box", "java_states": { "facing": "west" } },
    { "bedrock_states": { "color": "orange", "facing_direction": 5 }, "java_id": "minecraft:orange_shulker_box", "java_states": { "facing": "east" } },
    // magenta
    { "bedrock_states": { "color": "magenta", "facing_direction": 0 }, "java_id": "minecraft:magenta_shulker_box", "java_states": { "facing": "down" } },
    { "bedrock_states": { "color": "magenta", "facing_direction": 1 }, "java_id": "minecraft:magenta_shulker_box", "java_states": { "facing": "up" } },
    { "bedrock_states": { "color": "magenta", "facing_direction": 2 }, "java_id": "minecraft:magenta_shulker_box", "java_states": { "facing": "north" } },
    { "bedrock_states": { "color": "magenta", "facing_direction": 3 }, "java_id": "minecraft:magenta_shulker_box", "java_states": { "facing": "south" } },
    { "bedrock_states": { "color": "magenta", "facing_direction": 4 }, "java_id": "minecraft:magenta_shulker_box", "java_states": { "facing": "west" } },
    { "bedrock_states": { "color": "magenta", "facing_direction": 5 }, "java_id": "minecraft:magenta_shulker_box", "java_states": { "facing": "east" } },
    // light_blue
    { "bedrock_states": { "color": "light_blue", "facing_direction": 0 }, "java_id": "minecraft:light_blue_shulker_box", "java_states": { "facing": "down" } },
    { "bedrock_states": { "color": "light_blue", "facing_direction": 1 }, "java_id": "minecraft:light_blue_shulker_box", "java_states": { "facing": "up" } },
    { "bedrock_states": { "color": "light_blue", "facing_direction": 2 }, "java_id": "minecraft:light_blue_shulker_box", "java_states": { "facing": "north" } },
    { "bedrock_states": { "color": "light_blue", "facing_direction": 3 }, "java_id": "minecraft:light_blue_shulker_box", "java_states": { "facing": "south" } },
    { "bedrock_states": { "color": "light_blue", "facing_direction": 4 }, "java_id": "minecraft:light_blue_shulker_box", "java_states": { "facing": "west" } },
    { "bedrock_states": { "color": "light_blue", "facing_direction": 5 }, "java_id": "minecraft:light_blue_shulker_box", "java_states": { "facing": "east" } },
    // yellow
    { "bedrock_states": { "color": "yellow", "facing_direction": 0 }, "java_id": "minecraft:yellow_shulker_box", "java_states": { "facing": "down" } },
    { "bedrock_states": { "color": "yellow", "facing_direction": 1 }, "java_id": "minecraft:yellow_shulker_box", "java_states": { "facing": "up" } },
    { "bedrock_states": { "color": "yellow", "facing_direction": 2 }, "java_id": "minecraft:yellow_shulker_box", "java_states": { "facing": "north" } },
    { "bedrock_states": { "color": "yellow", "facing_direction": 3 }, "java_id": "minecraft:yellow_shulker_box", "java_states": { "facing": "south" } },
    { "bedrock_states": { "color": "yellow", "facing_direction": 4 }, "java_id": "minecraft:yellow_shulker_box", "java_states": { "facing": "west" } },
    { "bedrock_states": { "color": "yellow", "facing_direction": 5 }, "java_id": "minecraft:yellow_shulker_box", "java_states": { "facing": "east" } },
    // lime
    { "bedrock_states": { "color": "lime", "facing_direction": 0 }, "java_id": "minecraft:lime_shulker_box", "java_states": { "facing": "down" } },
    { "bedrock_states": { "color": "lime", "facing_direction": 1 }, "java_id": "minecraft:lime_shulker_box", "java_states": { "facing": "up" } },
    { "bedrock_states": { "color": "lime", "facing_direction": 2 }, "java_id": "minecraft:lime_shulker_box", "java_states": { "facing": "north" } },
    { "bedrock_states": { "color": "lime", "facing_direction": 3 }, "java_id": "minecraft:lime_shulker_box", "java_states": { "facing": "south" } },
    { "bedrock_states": { "color": "lime", "facing_direction": 4 }, "java_id": "minecraft:lime_shulker_box", "java_states": { "facing": "west" } },
    { "bedrock_states": { "color": "lime", "facing_direction": 5 }, "java_id": "minecraft:lime_shulker_box", "java_states": { "facing": "east" } },
    // pink
    { "bedrock_states": { "color": "pink", "facing_direction": 0 }, "java_id": "minecraft:pink_shulker_box", "java_states": { "facing": "down" } },
    { "bedrock_states": { "color": "pink", "facing_direction": 1 }, "java_id": "minecraft:pink_shulker_box", "java_states": { "facing": "up" } },
    { "bedrock_states": { "color": "pink", "facing_direction": 2 }, "java_id": "minecraft:pink_shulker_box", "java_states": { "facing": "north" } },
    { "bedrock_states": { "color": "pink", "facing_direction": 3 }, "java_id": "minecraft:pink_shulker_box", "java_states": { "facing": "south" } },
    { "bedrock_states": { "color": "pink", "facing_direction": 4 }, "java_id": "minecraft:pink_shulker_box", "java_states": { "facing": "west" } },
    { "bedrock_states": { "color": "pink", "facing_direction": 5 }, "java_id": "minecraft:pink_shulker_box", "java_states": { "facing": "east" } },
    // gray
    { "bedrock_states": { "color": "gray", "facing_direction": 0 }, "java_id": "minecraft:gray_shulker_box", "java_states": { "facing": "down" } },
    { "bedrock_states": { "color": "gray", "facing_direction": 1 }, "java_id": "minecraft:gray_shulker_box", "java_states": { "facing": "up" } },
    { "bedrock_states": { "color": "gray", "facing_direction": 2 }, "java_id": "minecraft:gray_shulker_box", "java_states": { "facing": "north" } },
    { "bedrock_states": { "color": "gray", "facing_direction": 3 }, "java_id": "minecraft:gray_shulker_box", "java_states": { "facing": "south" } },
    { "bedrock_states": { "color": "gray", "facing_direction": 4 }, "java_id": "minecraft:gray_shulker_box", "java_states": { "facing": "west" } },
    { "bedrock_states": { "color": "gray", "facing_direction": 5 }, "java_id": "minecraft:gray_shulker_box", "java_states": { "facing": "east" } },
    // silver → light_gray
    { "bedrock_states": { "color": "silver", "facing_direction": 0 }, "java_id": "minecraft:light_gray_shulker_box", "java_states": { "facing": "down" } },
    { "bedrock_states": { "color": "silver", "facing_direction": 1 }, "java_id": "minecraft:light_gray_shulker_box", "java_states": { "facing": "up" } },
    { "bedrock_states": { "color": "silver", "facing_direction": 2 }, "java_id": "minecraft:light_gray_shulker_box", "java_states": { "facing": "north" } },
    { "bedrock_states": { "color": "silver", "facing_direction": 3 }, "java_id": "minecraft:light_gray_shulker_box", "java_states": { "facing": "south" } },
    { "bedrock_states": { "color": "silver", "facing_direction": 4 }, "java_id": "minecraft:light_gray_shulker_box", "java_states": { "facing": "west" } },
    { "bedrock_states": { "color": "silver", "facing_direction": 5 }, "java_id": "minecraft:light_gray_shulker_box", "java_states": { "facing": "east" } },
    // cyan
    { "bedrock_states": { "color": "cyan", "facing_direction": 0 }, "java_id": "minecraft:cyan_shulker_box", "java_states": { "facing": "down" } },
    { "bedrock_states": { "color": "cyan", "facing_direction": 1 }, "java_id": "minecraft:cyan_shulker_box", "java_states": { "facing": "up" } },
    { "bedrock_states": { "color": "cyan", "facing_direction": 2 }, "java_id": "minecraft:cyan_shulker_box", "java_states": { "facing": "north" } },
    { "bedrock_states": { "color": "cyan", "facing_direction": 3 }, "java_id": "minecraft:cyan_shulker_box", "java_states": { "facing": "south" } },
    { "bedrock_states": { "color": "cyan", "facing_direction": 4 }, "java_id": "minecraft:cyan_shulker_box", "java_states": { "facing": "west" } },
    { "bedrock_states": { "color": "cyan", "facing_direction": 5 }, "java_id": "minecraft:cyan_shulker_box", "java_states": { "facing": "east" } },
    // purple
    { "bedrock_states": { "color": "purple", "facing_direction": 0 }, "java_id": "minecraft:purple_shulker_box", "java_states": { "facing": "down" } },
    { "bedrock_states": { "color": "purple", "facing_direction": 1 }, "java_id": "minecraft:purple_shulker_box", "java_states": { "facing": "up" } },
    { "bedrock_states": { "color": "purple", "facing_direction": 2 }, "java_id": "minecraft:purple_shulker_box", "java_states": { "facing": "north" } },
    { "bedrock_states": { "color": "purple", "facing_direction": 3 }, "java_id": "minecraft:purple_shulker_box", "java_states": { "facing": "south" } },
    { "bedrock_states": { "color": "purple", "facing_direction": 4 }, "java_id": "minecraft:purple_shulker_box", "java_states": { "facing": "west" } },
    { "bedrock_states": { "color": "purple", "facing_direction": 5 }, "java_id": "minecraft:purple_shulker_box", "java_states": { "facing": "east" } },
    // blue
    { "bedrock_states": { "color": "blue", "facing_direction": 0 }, "java_id": "minecraft:blue_shulker_box", "java_states": { "facing": "down" } },
    { "bedrock_states": { "color": "blue", "facing_direction": 1 }, "java_id": "minecraft:blue_shulker_box", "java_states": { "facing": "up" } },
    { "bedrock_states": { "color": "blue", "facing_direction": 2 }, "java_id": "minecraft:blue_shulker_box", "java_states": { "facing": "north" } },
    { "bedrock_states": { "color": "blue", "facing_direction": 3 }, "java_id": "minecraft:blue_shulker_box", "java_states": { "facing": "south" } },
    { "bedrock_states": { "color": "blue", "facing_direction": 4 }, "java_id": "minecraft:blue_shulker_box", "java_states": { "facing": "west" } },
    { "bedrock_states": { "color": "blue", "facing_direction": 5 }, "java_id": "minecraft:blue_shulker_box", "java_states": { "facing": "east" } },
    // brown
    { "bedrock_states": { "color": "brown", "facing_direction": 0 }, "java_id": "minecraft:brown_shulker_box", "java_states": { "facing": "down" } },
    { "bedrock_states": { "color": "brown", "facing_direction": 1 }, "java_id": "minecraft:brown_shulker_box", "java_states": { "facing": "up" } },
    { "bedrock_states": { "color": "brown", "facing_direction": 2 }, "java_id": "minecraft:brown_shulker_box", "java_states": { "facing": "north" } },
    { "bedrock_states": { "color": "brown", "facing_direction": 3 }, "java_id": "minecraft:brown_shulker_box", "java_states": { "facing": "south" } },
    { "bedrock_states": { "color": "brown", "facing_direction": 4 }, "java_id": "minecraft:brown_shulker_box", "java_states": { "facing": "west" } },
    { "bedrock_states": { "color": "brown", "facing_direction": 5 }, "java_id": "minecraft:brown_shulker_box", "java_states": { "facing": "east" } },
    // green
    { "bedrock_states": { "color": "green", "facing_direction": 0 }, "java_id": "minecraft:green_shulker_box", "java_states": { "facing": "down" } },
    { "bedrock_states": { "color": "green", "facing_direction": 1 }, "java_id": "minecraft:green_shulker_box", "java_states": { "facing": "up" } },
    { "bedrock_states": { "color": "green", "facing_direction": 2 }, "java_id": "minecraft:green_shulker_box", "java_states": { "facing": "north" } },
    { "bedrock_states": { "color": "green", "facing_direction": 3 }, "java_id": "minecraft:green_shulker_box", "java_states": { "facing": "south" } },
    { "bedrock_states": { "color": "green", "facing_direction": 4 }, "java_id": "minecraft:green_shulker_box", "java_states": { "facing": "west" } },
    { "bedrock_states": { "color": "green", "facing_direction": 5 }, "java_id": "minecraft:green_shulker_box", "java_states": { "facing": "east" } },
    // red
    { "bedrock_states": { "color": "red", "facing_direction": 0 }, "java_id": "minecraft:red_shulker_box", "java_states": { "facing": "down" } },
    { "bedrock_states": { "color": "red", "facing_direction": 1 }, "java_id": "minecraft:red_shulker_box", "java_states": { "facing": "up" } },
    { "bedrock_states": { "color": "red", "facing_direction": 2 }, "java_id": "minecraft:red_shulker_box", "java_states": { "facing": "north" } },
    { "bedrock_states": { "color": "red", "facing_direction": 3 }, "java_id": "minecraft:red_shulker_box", "java_states": { "facing": "south" } },
    { "bedrock_states": { "color": "red", "facing_direction": 4 }, "java_id": "minecraft:red_shulker_box", "java_states": { "facing": "west" } },
    { "bedrock_states": { "color": "red", "facing_direction": 5 }, "java_id": "minecraft:red_shulker_box", "java_states": { "facing": "east" } },
    // black
    { "bedrock_states": { "color": "black", "facing_direction": 0 }, "java_id": "minecraft:black_shulker_box", "java_states": { "facing": "down" } },
    { "bedrock_states": { "color": "black", "facing_direction": 1 }, "java_id": "minecraft:black_shulker_box", "java_states": { "facing": "up" } },
    { "bedrock_states": { "color": "black", "facing_direction": 2 }, "java_id": "minecraft:black_shulker_box", "java_states": { "facing": "north" } },
    { "bedrock_states": { "color": "black", "facing_direction": 3 }, "java_id": "minecraft:black_shulker_box", "java_states": { "facing": "south" } },
    { "bedrock_states": { "color": "black", "facing_direction": 4 }, "java_id": "minecraft:black_shulker_box", "java_states": { "facing": "west" } },
    { "bedrock_states": { "color": "black", "facing_direction": 5 }, "java_id": "minecraft:black_shulker_box", "java_states": { "facing": "east" } },
  ],

  // undyed shulker box → JE: minecraft:shulker_box
  "minecraft:undyed_shulker_box": [
    { "bedrock_states": { "facing_direction": 0 }, "java_id": "minecraft:shulker_box", "java_states": { "facing": "down" } },
    { "bedrock_states": { "facing_direction": 1 }, "java_id": "minecraft:shulker_box", "java_states": { "facing": "up" } },
    { "bedrock_states": { "facing_direction": 2 }, "java_id": "minecraft:shulker_box", "java_states": { "facing": "north" } },
    { "bedrock_states": { "facing_direction": 3 }, "java_id": "minecraft:shulker_box", "java_states": { "facing": "south" } },
    { "bedrock_states": { "facing_direction": 4 }, "java_id": "minecraft:shulker_box", "java_states": { "facing": "west" } },
    { "bedrock_states": { "facing_direction": 5 }, "java_id": "minecraft:shulker_box", "java_states": { "facing": "east" } },
  ],

  // ============================================================
  // SECTION 3: ベッド (Bed)
  // color: 0=white,1=orange,2=magenta,3=light_blue,4=yellow,5=lime,
  //        6=pink,7=gray,8=light_gray,9=cyan,10=purple,11=blue,
  //        12=brown,13=green,14=red,15=black
  // direction: 0=south,1=west,2=north,3=east
  // occupied_bit: 0=false,1=true
  // head_piece_bit: 0=foot,1=head
  // ============================================================

  "minecraft:bed": [
    // --- color 0: white ---
    { "bedrock_states": { "color": 0, "direction": 0, "occupied_bit": 0, "head_piece_bit": 0 }, "java_id": "minecraft:white_bed", "java_states": { "facing": "south", "occupied": "false", "part": "foot" } },
    { "bedrock_states": { "color": 0, "direction": 0, "occupied_bit": 0, "head_piece_bit": 1 }, "java_id": "minecraft:white_bed", "java_states": { "facing": "south", "occupied": "false", "part": "head" } },
    { "bedrock_states": { "color": 0, "direction": 0, "occupied_bit": 1, "head_piece_bit": 0 }, "java_id": "minecraft:white_bed", "java_states": { "facing": "south", "occupied": "true", "part": "foot" } },
    { "bedrock_states": { "color": 0, "direction": 0, "occupied_bit": 1, "head_piece_bit": 1 }, "java_id": "minecraft:white_bed", "java_states": { "facing": "south", "occupied": "true", "part": "head" } },
    { "bedrock_states": { "color": 0, "direction": 1, "occupied_bit": 0, "head_piece_bit": 0 }, "java_id": "minecraft:white_bed", "java_states": { "facing": "west", "occupied": "false", "part": "foot" } },
    { "bedrock_states": { "color": 0, "direction": 1, "occupied_bit": 0, "head_piece_bit": 1 }, "java_id": "minecraft:white_bed", "java_states": { "facing": "west", "occupied": "false", "part": "head" } },
    { "bedrock_states": { "color": 0, "direction": 1, "occupied_bit": 1, "head_piece_bit": 0 }, "java_id": "minecraft:white_bed", "java_states": { "facing": "west", "occupied": "true", "part": "foot" } },
    { "bedrock_states": { "color": 0, "direction": 1, "occupied_bit": 1, "head_piece_bit": 1 }, "java_id": "minecraft:white_bed", "java_states": { "facing": "west", "occupied": "true", "part": "head" } },
    { "bedrock_states": { "color": 0, "direction": 2, "occupied_bit": 0, "head_piece_bit": 0 }, "java_id": "minecraft:white_bed", "java_states": { "facing": "north", "occupied": "false", "part": "foot" } },
    { "bedrock_states": { "color": 0, "direction": 2, "occupied_bit": 0, "head_piece_bit": 1 }, "java_id": "minecraft:white_bed", "java_states": { "facing": "north", "occupied": "false", "part": "head" } },
    { "bedrock_states": { "color": 0, "direction": 2, "occupied_bit": 1, "head_piece_bit": 0 }, "java_id": "minecraft:white_bed", "java_states": { "facing": "north", "occupied": "true", "part": "foot" } },
    { "bedrock_states": { "color": 0, "direction": 2, "occupied_bit": 1, "head_piece_bit": 1 }, "java_id": "minecraft:white_bed", "java_states": { "facing": "north", "occupied": "true", "part": "head" } },
    { "bedrock_states": { "color": 0, "direction": 3, "occupied_bit": 0, "head_piece_bit": 0 }, "java_id": "minecraft:white_bed", "java_states": { "facing": "east", "occupied": "false", "part": "foot" } },
    { "bedrock_states": { "color": 0, "direction": 3, "occupied_bit": 0, "head_piece_bit": 1 }, "java_id": "minecraft:white_bed", "java_states": { "facing": "east", "occupied": "false", "part": "head" } },
    { "bedrock_states": { "color": 0, "direction": 3, "occupied_bit": 1, "head_piece_bit": 0 }, "java_id": "minecraft:white_bed", "java_states": { "facing": "east", "occupied": "true", "part": "foot" } },
    { "bedrock_states": { "color": 0, "direction": 3, "occupied_bit": 1, "head_piece_bit": 1 }, "java_id": "minecraft:white_bed", "java_states": { "facing": "east", "occupied": "true", "part": "head" } },
    // --- color 1: orange ---
    { "bedrock_states": { "color": 1, "direction": 0, "occupied_bit": 0, "head_piece_bit": 0 }, "java_id": "minecraft:orange_bed", "java_states": { "facing": "south", "occupied": "false", "part": "foot" } },
    { "bedrock_states": { "color": 1, "direction": 0, "occupied_bit": 0, "head_piece_bit": 1 }, "java_id": "minecraft:orange_bed", "java_states": { "facing": "south", "occupied": "false", "part": "head" } },
    { "bedrock_states": { "color": 1, "direction": 0, "occupied_bit": 1, "head_piece_bit": 0 }, "java_id": "minecraft:orange_bed", "java_states": { "facing": "south", "occupied": "true", "part": "foot" } },
    { "bedrock_states": { "color": 1, "direction": 0, "occupied_bit": 1, "head_piece_bit": 1 }, "java_id": "minecraft:orange_bed", "java_states": { "facing": "south", "occupied": "true", "part": "head" } },
    { "bedrock_states": { "color": 1, "direction": 1, "occupied_bit": 0, "head_piece_bit": 0 }, "java_id": "minecraft:orange_bed", "java_states": { "facing": "west", "occupied": "false", "part": "foot" } },
    { "bedrock_states": { "color": 1, "direction": 1, "occupied_bit": 0, "head_piece_bit": 1 }, "java_id": "minecraft:orange_bed", "java_states": { "facing": "west", "occupied": "false", "part": "head" } },
    { "bedrock_states": { "color": 1, "direction": 1, "occupied_bit": 1, "head_piece_bit": 0 }, "java_id": "minecraft:orange_bed", "java_states": { "facing": "west", "occupied": "true", "part": "foot" } },
    { "bedrock_states": { "color": 1, "direction": 1, "occupied_bit": 1, "head_piece_bit": 1 }, "java_id": "minecraft:orange_bed", "java_states": { "facing": "west", "occupied": "true", "part": "head" } },
    { "bedrock_states": { "color": 1, "direction": 2, "occupied_bit": 0, "head_piece_bit": 0 }, "java_id": "minecraft:orange_bed", "java_states": { "facing": "north", "occupied": "false", "part": "foot" } },
    { "bedrock_states": { "color": 1, "direction": 2, "occupied_bit": 0, "head_piece_bit": 1 }, "java_id": "minecraft:orange_bed", "java_states": { "facing": "north", "occupied": "false", "part": "head" } },
    { "bedrock_states": { "color": 1, "direction": 2, "occupied_bit": 1, "head_piece_bit": 0 }, "java_id": "minecraft:orange_bed", "java_states": { "facing": "north", "occupied": "true", "part": "foot" } },
    { "bedrock_states": { "color": 1, "direction": 2, "occupied_bit": 1, "head_piece_bit": 1 }, "java_id": "minecraft:orange_bed", "java_states": { "facing": "north", "occupied": "true", "part": "head" } },
    { "bedrock_states": { "color": 1, "direction": 3, "occupied_bit": 0, "head_piece_bit": 0 }, "java_id": "minecraft:orange_bed", "java_states": { "facing": "east", "occupied": "false", "part": "foot" } },
    { "bedrock_states": { "color": 1, "direction": 3, "occupied_bit": 0, "head_piece_bit": 1 }, "java_id": "minecraft:orange_bed", "java_states": { "facing": "east", "occupied": "false", "part": "head" } },
    { "bedrock_states": { "color": 1, "direction": 3, "occupied_bit": 1, "head_piece_bit": 0 }, "java_id": "minecraft:orange_bed", "java_states": { "facing": "east", "occupied": "true", "part": "foot" } },
    { "bedrock_states": { "color": 1, "direction": 3, "occupied_bit": 1, "head_piece_bit": 1 }, "java_id": "minecraft:orange_bed", "java_states": { "facing": "east", "occupied": "true", "part": "head" } },
    // --- color 2: magenta ---
    { "bedrock_states": { "color": 2, "direction": 0, "occupied_bit": 0, "head_piece_bit": 0 }, "java_id": "minecraft:magenta_bed", "java_states": { "facing": "south", "occupied": "false", "part": "foot" } },
    { "bedrock_states": { "color": 2, "direction": 0, "occupied_bit": 0, "head_piece_bit": 1 }, "java_id": "minecraft:magenta_bed", "java_states": { "facing": "south", "occupied": "false", "part": "head" } },
    { "bedrock_states": { "color": 2, "direction": 0, "occupied_bit": 1, "head_piece_bit": 0 }, "java_id": "minecraft:magenta_bed", "java_states": { "facing": "south", "occupied": "true", "part": "foot" } },
    { "bedrock_states": { "color": 2, "direction": 0, "occupied_bit": 1, "head_piece_bit": 1 }, "java_id": "minecraft:magenta_bed", "java_states": { "facing": "south", "occupied": "true", "part": "head" } },
    { "bedrock_states": { "color": 2, "direction": 1, "occupied_bit": 0, "head_piece_bit": 0 }, "java_id": "minecraft:magenta_bed", "java_states": { "facing": "west", "occupied": "false", "part": "foot" } },
    { "bedrock_states": { "color": 2, "direction": 1, "occupied_bit": 0, "head_piece_bit": 1 }, "java_id": "minecraft:magenta_bed", "java_states": { "facing": "west", "occupied": "false", "part": "head" } },
    { "bedrock_states": { "color": 2, "direction": 1, "occupied_bit": 1, "head_piece_bit": 0 }, "java_id": "minecraft:magenta_bed", "java_states": { "facing": "west", "occupied": "true", "part": "foot" } },
    { "bedrock_states": { "color": 2, "direction": 1, "occupied_bit": 1, "head_piece_bit": 1 }, "java_id": "minecraft:magenta_bed", "java_states": { "facing": "west", "occupied": "true", "part": "head" } },
    { "bedrock_states": { "color": 2, "direction": 2, "occupied_bit": 0, "head_piece_bit": 0 }, "java_id": "minecraft:magenta_bed", "java_states": { "facing": "north", "occupied": "false", "part": "foot" } },
    { "bedrock_states": { "color": 2, "direction": 2, "occupied_bit": 0, "head_piece_bit": 1 }, "java_id": "minecraft:magenta_bed", "java_states": { "facing": "north", "occupied": "false", "part": "head" } },
    { "bedrock_states": { "color": 2, "direction": 2, "occupied_bit": 1, "head_piece_bit": 0 }, "java_id": "minecraft:magenta_bed", "java_states": { "facing": "north", "occupied": "true", "part": "foot" } },
    { "bedrock_states": { "color": 2, "direction": 2, "occupied_bit": 1, "head_piece_bit": 1 }, "java_id": "minecraft:magenta_bed", "java_states": { "facing": "north", "occupied": "true", "part": "head" } },
    { "bedrock_states": { "color": 2, "direction": 3, "occupied_bit": 0, "head_piece_bit": 0 }, "java_id": "minecraft:magenta_bed", "java_states": { "facing": "east", "occupied": "false", "part": "foot" } },
    { "bedrock_states": { "color": 2, "direction": 3, "occupied_bit": 0, "head_piece_bit": 1 }, "java_id": "minecraft:magenta_bed", "java_states": { "facing": "east", "occupied": "false", "part": "head" } },
    { "bedrock_states": { "color": 2, "direction": 3, "occupied_bit": 1, "head_piece_bit": 0 }, "java_id": "minecraft:magenta_bed", "java_states": { "facing": "east", "occupied": "true", "part": "foot" } },
    { "bedrock_states": { "color": 2, "direction": 3, "occupied_bit": 1, "head_piece_bit": 1 }, "java_id": "minecraft:magenta_bed", "java_states": { "facing": "east", "occupied": "true", "part": "head" } },
    // --- color 3: light_blue ---
    { "bedrock_states": { "color": 3, "direction": 0, "occupied_bit": 0, "head_piece_bit": 0 }, "java_id": "minecraft:light_blue_bed", "java_states": { "facing": "south", "occupied": "false", "part": "foot" } },
    { "bedrock_states": { "color": 3, "direction": 0, "occupied_bit": 0, "head_piece_bit": 1 }, "java_id": "minecraft:light_blue_bed", "java_states": { "facing": "south", "occupied": "false", "part": "head" } },
    { "bedrock_states": { "color": 3, "direction": 0, "occupied_bit": 1, "head_piece_bit": 0 }, "java_id": "minecraft:light_blue_bed", "java_states": { "facing": "south", "occupied": "true", "part": "foot" } },
    { "bedrock_states": { "color": 3, "direction": 0, "occupied_bit": 1, "head_piece_bit": 1 }, "java_id": "minecraft:light_blue_bed", "java_states": { "facing": "south", "occupied": "true", "part": "head" } },
    { "bedrock_states": { "color": 3, "direction": 1, "occupied_bit": 0, "head_piece_bit": 0 }, "java_id": "minecraft:light_blue_bed", "java_states": { "facing": "west", "occupied": "false", "part": "foot" } },
    { "bedrock_states": { "color": 3, "direction": 1, "occupied_bit": 0, "head_piece_bit": 1 }, "java_id": "minecraft:light_blue_bed", "java_states": { "facing": "west", "occupied": "false", "part": "head" } },
    { "bedrock_states": { "color": 3, "direction": 1, "occupied_bit": 1, "head_piece_bit": 0 }, "java_id": "minecraft:light_blue_bed", "java_states": { "facing": "west", "occupied": "true", "part": "foot" } },
    { "bedrock_states": { "color": 3, "direction": 1, "occupied_bit": 1, "head_piece_bit": 1 }, "java_id": "minecraft:light_blue_bed", "java_states": { "facing": "west", "occupied": "true", "part": "head" } },
    { "bedrock_states": { "color": 3, "direction": 2, "occupied_bit": 0, "head_piece_bit": 0 }, "java_id": "minecraft:light_blue_bed", "java_states": { "facing": "north", "occupied": "false", "part": "foot" } },
    { "bedrock_states": { "color": 3, "direction": 2, "occupied_bit": 0, "head_piece_bit": 1 }, "java_id": "minecraft:light_blue_bed", "java_states": { "facing": "north", "occupied": "false", "part": "head" } },
    { "bedrock_states": { "color": 3, "direction": 2, "occupied_bit": 1, "head_piece_bit": 0 }, "java_id": "minecraft:light_blue_bed", "java_states": { "facing": "north", "occupied": "true", "part": "foot" } },
    { "bedrock_states": { "color": 3, "direction": 2, "occupied_bit": 1, "head_piece_bit": 1 }, "java_id": "minecraft:light_blue_bed", "java_states": { "facing": "north", "occupied": "true", "part": "head" } },
    { "bedrock_states": { "color": 3, "direction": 3, "occupied_bit": 0, "head_piece_bit": 0 }, "java_id": "minecraft:light_blue_bed", "java_states": { "facing": "east", "occupied": "false", "part": "foot" } },
    { "bedrock_states": { "color": 3, "direction": 3, "occupied_bit": 0, "head_piece_bit": 1 }, "java_id": "minecraft:light_blue_bed", "java_states": { "facing": "east", "occupied": "false", "part": "head" } },
    { "bedrock_states": { "color": 3, "direction": 3, "occupied_bit": 1, "head_piece_bit": 0 }, "java_id": "minecraft:light_blue_bed", "java_states": { "facing": "east", "occupied": "true", "part": "foot" } },
    { "bedrock_states": { "color": 3, "direction": 3, "occupied_bit": 1, "head_piece_bit": 1 }, "java_id": "minecraft:light_blue_bed", "java_states": { "facing": "east", "occupied": "true", "part": "head" } },
    // --- color 4: yellow ---
    { "bedrock_states": { "color": 4, "direction": 0, "occupied_bit": 0, "head_piece_bit": 0 }, "java_id": "minecraft:yellow_bed", "java_states": { "facing": "south", "occupied": "false", "part": "foot" } },
    { "bedrock_states": { "color": 4, "direction": 0, "occupied_bit": 0, "head_piece_bit": 1 }, "java_id": "minecraft:yellow_bed", "java_states": { "facing": "south", "occupied": "false", "part": "head" } },
    { "bedrock_states": { "color": 4, "direction": 0, "occupied_bit": 1, "head_piece_bit": 0 }, "java_id": "minecraft:yellow_bed", "java_states": { "facing": "south", "occupied": "true", "part": "foot" } },
    { "bedrock_states": { "color": 4, "direction": 0, "occupied_bit": 1, "head_piece_bit": 1 }, "java_id": "minecraft:yellow_bed", "java_states": { "facing": "south", "occupied": "true", "part": "head" } },
    { "bedrock_states": { "color": 4, "direction": 1, "occupied_bit": 0, "head_piece_bit": 0 }, "java_id": "minecraft:yellow_bed", "java_states": { "facing": "west", "occupied": "false", "part": "foot" } },
    { "bedrock_states": { "color": 4, "direction": 1, "occupied_bit": 0, "head_piece_bit": 1 }, "java_id": "minecraft:yellow_bed", "java_states": { "facing": "west", "occupied": "false", "part": "head" } },
    { "bedrock_states": { "color": 4, "direction": 1, "occupied_bit": 1, "head_piece_bit": 0 }, "java_id": "minecraft:yellow_bed", "java_states": { "facing": "west", "occupied": "true", "part": "foot" } },
    { "bedrock_states": { "color": 4, "direction": 1, "occupied_bit": 1, "head_piece_bit": 1 }, "java_id": "minecraft:yellow_bed", "java_states": { "facing": "west", "occupied": "true", "part": "head" } },
    { "bedrock_states": { "color": 4, "direction": 2, "occupied_bit": 0, "head_piece_bit": 0 }, "java_id": "minecraft:yellow_bed", "java_states": { "facing": "north", "occupied": "false", "part": "foot" } },
    { "bedrock_states": { "color": 4, "direction": 2, "occupied_bit": 0, "head_piece_bit": 1 }, "java_id": "minecraft:yellow_bed", "java_states": { "facing": "north", "occupied": "false", "part": "head" } },
    { "bedrock_states": { "color": 4, "direction": 2, "occupied_bit": 1, "head_piece_bit": 0 }, "java_id": "minecraft:yellow_bed", "java_states": { "facing": "north", "occupied": "true", "part": "foot" } },
    { "bedrock_states": { "color": 4, "direction": 2, "occupied_bit": 1, "head_piece_bit": 1 }, "java_id": "minecraft:yellow_bed", "java_states": { "facing": "north", "occupied": "true", "part": "head" } },
    { "bedrock_states": { "color": 4, "direction": 3, "occupied_bit": 0, "head_piece_bit": 0 }, "java_id": "minecraft:yellow_bed", "java_states": { "facing": "east", "occupied": "false", "part": "foot" } },
    { "bedrock_states": { "color": 4, "direction": 3, "occupied_bit": 0, "head_piece_bit": 1 }, "java_id": "minecraft:yellow_bed", "java_states": { "facing": "east", "occupied": "false", "part": "head" } },
    { "bedrock_states": { "color": 4, "direction": 3, "occupied_bit": 1, "head_piece_bit": 0 }, "java_id": "minecraft:yellow_bed", "java_states": { "facing": "east", "occupied": "true", "part": "foot" } },
    { "bedrock_states": { "color": 4, "direction": 3, "occupied_bit": 1, "head_piece_bit": 1 }, "java_id": "minecraft:yellow_bed", "java_states": { "facing": "east", "occupied": "true", "part": "head" } },
    // --- color 5: lime ---
    { "bedrock_states": { "color": 5, "direction": 0, "occupied_bit": 0, "head_piece_bit": 0 }, "java_id": "minecraft:lime_bed", "java_states": { "facing": "south", "occupied": "false", "part": "foot" } },
    { "bedrock_states": { "color": 5, "direction": 0, "occupied_bit": 0, "head_piece_bit": 1 }, "java_id": "minecraft:lime_bed", "java_states": { "facing": "south", "occupied": "false", "part": "head" } },
    { "bedrock_states": { "color": 5, "direction": 0, "occupied_bit": 1, "head_piece_bit": 0 }, "java_id": "minecraft:lime_bed", "java_states": { "facing": "south", "occupied": "true", "part": "foot" } },
    { "bedrock_states": { "color": 5, "direction": 0, "occupied_bit": 1, "head_piece_bit": 1 }, "java_id": "minecraft:lime_bed", "java_states": { "facing": "south", "occupied": "true", "part": "head" } },
    { "bedrock_states": { "color": 5, "direction": 1, "occupied_bit": 0, "head_piece_bit": 0 }, "java_id": "minecraft:lime_bed", "java_states": { "facing": "west", "occupied": "false", "part": "foot" } },
    { "bedrock_states": { "color": 5, "direction": 1, "occupied_bit": 0, "head_piece_bit": 1 }, "java_id": "minecraft:lime_bed", "java_states": { "facing": "west", "occupied": "false", "part": "head" } },
    { "bedrock_states": { "color": 5, "direction": 1, "occupied_bit": 1, "head_piece_bit": 0 }, "java_id": "minecraft:lime_bed", "java_states": { "facing": "west", "occupied": "true", "part": "foot" } },
    { "bedrock_states": { "color": 5, "direction": 1, "occupied_bit": 1, "head_piece_bit": 1 }, "java_id": "minecraft:lime_bed", "java_states": { "facing": "west", "occupied": "true", "part": "head" } },
    { "bedrock_states": { "color": 5, "direction": 2, "occupied_bit": 0, "head_piece_bit": 0 }, "java_id": "minecraft:lime_bed", "java_states": { "facing": "north", "occupied": "false", "part": "foot" } },
    { "bedrock_states": { "color": 5, "direction": 2, "occupied_bit": 0, "head_piece_bit": 1 }, "java_id": "minecraft:lime_bed", "java_states": { "facing": "north", "occupied": "false", "part": "head" } },
    { "bedrock_states": { "color": 5, "direction": 2, "occupied_bit": 1, "head_piece_bit": 0 }, "java_id": "minecraft:lime_bed", "java_states": { "facing": "north", "occupied": "true", "part": "foot" } },
    { "bedrock_states": { "color": 5, "direction": 2, "occupied_bit": 1, "head_piece_bit": 1 }, "java_id": "minecraft:lime_bed", "java_states": { "facing": "north", "occupied": "true", "part": "head" } },
    { "bedrock_states": { "color": 5, "direction": 3, "occupied_bit": 0, "head_piece_bit": 0 }, "java_id": "minecraft:lime_bed", "java_states": { "facing": "east", "occupied": "false", "part": "foot" } },
    { "bedrock_states": { "color": 5, "direction": 3, "occupied_bit": 0, "head_piece_bit": 1 }, "java_id": "minecraft:lime_bed", "java_states": { "facing": "east", "occupied": "false", "part": "head" } },
    { "bedrock_states": { "color": 5, "direction": 3, "occupied_bit": 1, "head_piece_bit": 0 }, "java_id": "minecraft:lime_bed", "java_states": { "facing": "east", "occupied": "true", "part": "foot" } },
    { "bedrock_states": { "color": 5, "direction": 3, "occupied_bit": 1, "head_piece_bit": 1 }, "java_id": "minecraft:lime_bed", "java_states": { "facing": "east", "occupied": "true", "part": "head" } },
    // --- color 6: pink ---
    { "bedrock_states": { "color": 6, "direction": 0, "occupied_bit": 0, "head_piece_bit": 0 }, "java_id": "minecraft:pink_bed", "java_states": { "facing": "south", "occupied": "false", "part": "foot" } },
    { "bedrock_states": { "color": 6, "direction": 0, "occupied_bit": 0, "head_piece_bit": 1 }, "java_id": "minecraft:pink_bed", "java_states": { "facing": "south", "occupied": "false", "part": "head" } },
    { "bedrock_states": { "color": 6, "direction": 0, "occupied_bit": 1, "head_piece_bit": 0 }, "java_id": "minecraft:pink_bed", "java_states": { "facing": "south", "occupied": "true", "part": "foot" } },
    { "bedrock_states": { "color": 6, "direction": 0, "occupied_bit": 1, "head_piece_bit": 1 }, "java_id": "minecraft:pink_bed", "java_states": { "facing": "south", "occupied": "true", "part": "head" } },
    { "bedrock_states": { "color": 6, "direction": 1, "occupied_bit": 0, "head_piece_bit": 0 }, "java_id": "minecraft:pink_bed", "java_states": { "facing": "west", "occupied": "false", "part": "foot" } },
    { "bedrock_states": { "color": 6, "direction": 1, "occupied_bit": 0, "head_piece_bit": 1 }, "java_id": "minecraft:pink_bed", "java_states": { "facing": "west", "occupied": "false", "part": "head" } },
    { "bedrock_states": { "color": 6, "direction": 1, "occupied_bit": 1, "head_piece_bit": 0 }, "java_id": "minecraft:pink_bed", "java_states": { "facing": "west", "occupied": "true", "part": "foot" } },
    { "bedrock_states": { "color": 6, "direction": 1, "occupied_bit": 1, "head_piece_bit": 1 }, "java_id": "minecraft:pink_bed", "java_states": { "facing": "west", "occupied": "true", "part": "head" } },
    { "bedrock_states": { "color": 6, "direction": 2, "occupied_bit": 0, "head_piece_bit": 0 }, "java_id": "minecraft:pink_bed", "java_states": { "facing": "north", "occupied": "false", "part": "foot" } },
    { "bedrock_states": { "color": 6, "direction": 2, "occupied_bit": 0, "head_piece_bit": 1 }, "java_id": "minecraft:pink_bed", "java_states": { "facing": "north", "occupied": "false", "part": "head" } },
    { "bedrock_states": { "color": 6, "direction": 2, "occupied_bit": 1, "head_piece_bit": 0 }, "java_id": "minecraft:pink_bed", "java_states": { "facing": "north", "occupied": "true", "part": "foot" } },
    { "bedrock_states": { "color": 6, "direction": 2, "occupied_bit": 1, "head_piece_bit": 1 }, "java_id": "minecraft:pink_bed", "java_states": { "facing": "north", "occupied": "true", "part": "head" } },
    { "bedrock_states": { "color": 6, "direction": 3, "occupied_bit": 0, "head_piece_bit": 0 }, "java_id": "minecraft:pink_bed", "java_states": { "facing": "east", "occupied": "false", "part": "foot" } },
    { "bedrock_states": { "color": 6, "direction": 3, "occupied_bit": 0, "head_piece_bit": 1 }, "java_id": "minecraft:pink_bed", "java_states": { "facing": "east", "occupied": "false", "part": "head" } },
    { "bedrock_states": { "color": 6, "direction": 3, "occupied_bit": 1, "head_piece_bit": 0 }, "java_id": "minecraft:pink_bed", "java_states": { "facing": "east", "occupied": "true", "part": "foot" } },
    { "bedrock_states": { "color": 6, "direction": 3, "occupied_bit": 1, "head_piece_bit": 1 }, "java_id": "minecraft:pink_bed", "java_states": { "facing": "east", "occupied": "true", "part": "head" } },
    // --- color 7: gray ---
    { "bedrock_states": { "color": 7, "direction": 0, "occupied_bit": 0, "head_piece_bit": 0 }, "java_id": "minecraft:gray_bed", "java_states": { "facing": "south", "occupied": "false", "part": "foot" } },
    { "bedrock_states": { "color": 7, "direction": 0, "occupied_bit": 0, "head_piece_bit": 1 }, "java_id": "minecraft:gray_bed", "java_states": { "facing": "south", "occupied": "false", "part": "head" } },
    { "bedrock_states": { "color": 7, "direction": 0, "occupied_bit": 1, "head_piece_bit": 0 }, "java_id": "minecraft:gray_bed", "java_states": { "facing": "south", "occupied": "true", "part": "foot" } },
    { "bedrock_states": { "color": 7, "direction": 0, "occupied_bit": 1, "head_piece_bit": 1 }, "java_id": "minecraft:gray_bed", "java_states": { "facing": "south", "occupied": "true", "part": "head" } },
    { "bedrock_states": { "color": 7, "direction": 1, "occupied_bit": 0, "head_piece_bit": 0 }, "java_id": "minecraft:gray_bed", "java_states": { "facing": "west", "occupied": "false", "part": "foot" } },
    { "bedrock_states": { "color": 7, "direction": 1, "occupied_bit": 0, "head_piece_bit": 1 }, "java_id": "minecraft:gray_bed", "java_states": { "facing": "west", "occupied": "false", "part": "head" } },
    { "bedrock_states": { "color": 7, "direction": 1, "occupied_bit": 1, "head_piece_bit": 0 }, "java_id": "minecraft:gray_bed", "java_states": { "facing": "west", "occupied": "true", "part": "foot" } },
    { "bedrock_states": { "color": 7, "direction": 1, "occupied_bit": 1, "head_piece_bit": 1 }, "java_id": "minecraft:gray_bed", "java_states": { "facing": "west", "occupied": "true", "part": "head" } },
    { "bedrock_states": { "color": 7, "direction": 2, "occupied_bit": 0, "head_piece_bit": 0 }, "java_id": "minecraft:gray_bed", "java_states": { "facing": "north", "occupied": "false", "part": "foot" } },
    { "bedrock_states": { "color": 7, "direction": 2, "occupied_bit": 0, "head_piece_bit": 1 }, "java_id": "minecraft:gray_bed", "java_states": { "facing": "north", "occupied": "false", "part": "head" } },
    { "bedrock_states": { "color": 7, "direction": 2, "occupied_bit": 1, "head_piece_bit": 0 }, "java_id": "minecraft:gray_bed", "java_states": { "facing": "north", "occupied": "true", "part": "foot" } },
    { "bedrock_states": { "color": 7, "direction": 2, "occupied_bit": 1, "head_piece_bit": 1 }, "java_id": "minecraft:gray_bed", "java_states": { "facing": "north", "occupied": "true", "part": "head" } },
    { "bedrock_states": { "color": 7, "direction": 3, "occupied_bit": 0, "head_piece_bit": 0 }, "java_id": "minecraft:gray_bed", "java_states": { "facing": "east", "occupied": "false", "part": "foot" } },
    { "bedrock_states": { "color": 7, "direction": 3, "occupied_bit": 0, "head_piece_bit": 1 }, "java_id": "minecraft:gray_bed", "java_states": { "facing": "east", "occupied": "false", "part": "head" } },
    { "bedrock_states": { "color": 7, "direction": 3, "occupied_bit": 1, "head_piece_bit": 0 }, "java_id": "minecraft:gray_bed", "java_states": { "facing": "east", "occupied": "true", "part": "foot" } },
    { "bedrock_states": { "color": 7, "direction": 3, "occupied_bit": 1, "head_piece_bit": 1 }, "java_id": "minecraft:gray_bed", "java_states": { "facing": "east", "occupied": "true", "part": "head" } },
    // --- color 8: light_gray ---
    { "bedrock_states": { "color": 8, "direction": 0, "occupied_bit": 0, "head_piece_bit": 0 }, "java_id": "minecraft:light_gray_bed", "java_states": { "facing": "south", "occupied": "false", "part": "foot" } },
    { "bedrock_states": { "color": 8, "direction": 0, "occupied_bit": 0, "head_piece_bit": 1 }, "java_id": "minecraft:light_gray_bed", "java_states": { "facing": "south", "occupied": "false", "part": "head" } },
    { "bedrock_states": { "color": 8, "direction": 0, "occupied_bit": 1, "head_piece_bit": 0 }, "java_id": "minecraft:light_gray_bed", "java_states": { "facing": "south", "occupied": "true", "part": "foot" } },
    { "bedrock_states": { "color": 8, "direction": 0, "occupied_bit": 1, "head_piece_bit": 1 }, "java_id": "minecraft:light_gray_bed", "java_states": { "facing": "south", "occupied": "true", "part": "head" } },
    { "bedrock_states": { "color": 8, "direction": 1, "occupied_bit": 0, "head_piece_bit": 0 }, "java_id": "minecraft:light_gray_bed", "java_states": { "facing": "west", "occupied": "false", "part": "foot" } },
    { "bedrock_states": { "color": 8, "direction": 1, "occupied_bit": 0, "head_piece_bit": 1 }, "java_id": "minecraft:light_gray_bed", "java_states": { "facing": "west", "occupied": "false", "part": "head" } },
    { "bedrock_states": { "color": 8, "direction": 1, "occupied_bit": 1, "head_piece_bit": 0 }, "java_id": "minecraft:light_gray_bed", "java_states": { "facing": "west", "occupied": "true", "part": "foot" } },
    { "bedrock_states": { "color": 8, "direction": 1, "occupied_bit": 1, "head_piece_bit": 1 }, "java_id": "minecraft:light_gray_bed", "java_states": { "facing": "west", "occupied": "true", "part": "head" } },
    { "bedrock_states": { "color": 8, "direction": 2, "occupied_bit": 0, "head_piece_bit": 0 }, "java_id": "minecraft:light_gray_bed", "java_states": { "facing": "north", "occupied": "false", "part": "foot" } },
    { "bedrock_states": { "color": 8, "direction": 2, "occupied_bit": 0, "head_piece_bit": 1 }, "java_id": "minecraft:light_gray_bed", "java_states": { "facing": "north", "occupied": "false", "part": "head" } },
    { "bedrock_states": { "color": 8, "direction": 2, "occupied_bit": 1, "head_piece_bit": 0 }, "java_id": "minecraft:light_gray_bed", "java_states": { "facing": "north", "occupied": "true", "part": "foot" } },
    { "bedrock_states": { "color": 8, "direction": 2, "occupied_bit": 1, "head_piece_bit": 1 }, "java_id": "minecraft:light_gray_bed", "java_states": { "facing": "north", "occupied": "true", "part": "head" } },
    { "bedrock_states": { "color": 8, "direction": 3, "occupied_bit": 0, "head_piece_bit": 0 }, "java_id": "minecraft:light_gray_bed", "java_states": { "facing": "east", "occupied": "false", "part": "foot" } },
    { "bedrock_states": { "color": 8, "direction": 3, "occupied_bit": 0, "head_piece_bit": 1 }, "java_id": "minecraft:light_gray_bed", "java_states": { "facing": "east", "occupied": "false", "part": "head" } },
    { "bedrock_states": { "color": 8, "direction": 3, "occupied_bit": 1, "head_piece_bit": 0 }, "java_id": "minecraft:light_gray_bed", "java_states": { "facing": "east", "occupied": "true", "part": "foot" } },
    { "bedrock_states": { "color": 8, "direction": 3, "occupied_bit": 1, "head_piece_bit": 1 }, "java_id": "minecraft:light_gray_bed", "java_states": { "facing": "east", "occupied": "true", "part": "head" } },
    // --- color 9: cyan ---
    { "bedrock_states": { "color": 9, "direction": 0, "occupied_bit": 0, "head_piece_bit": 0 }, "java_id": "minecraft:cyan_bed", "java_states": { "facing": "south", "occupied": "false", "part": "foot" } },
    { "bedrock_states": { "color": 9, "direction": 0, "occupied_bit": 0, "head_piece_bit": 1 }, "java_id": "minecraft:cyan_bed", "java_states": { "facing": "south", "occupied": "false", "part": "head" } },
    { "bedrock_states": { "color": 9, "direction": 0, "occupied_bit": 1, "head_piece_bit": 0 }, "java_id": "minecraft:cyan_bed", "java_states": { "facing": "south", "occupied": "true", "part": "foot" } },
    { "bedrock_states": { "color": 9, "direction": 0, "occupied_bit": 1, "head_piece_bit": 1 }, "java_id": "minecraft:cyan_bed", "java_states": { "facing": "south", "occupied": "true", "part": "head" } },
    { "bedrock_states": { "color": 9, "direction": 1, "occupied_bit": 0, "head_piece_bit": 0 }, "java_id": "minecraft:cyan_bed", "java_states": { "facing": "west", "occupied": "false", "part": "foot" } },
    { "bedrock_states": { "color": 9, "direction": 1, "occupied_bit": 0, "head_piece_bit": 1 }, "java_id": "minecraft:cyan_bed", "java_states": { "facing": "west", "occupied": "false", "part": "head" } },
    { "bedrock_states": { "color": 9, "direction": 1, "occupied_bit": 1, "head_piece_bit": 0 }, "java_id": "minecraft:cyan_bed", "java_states": { "facing": "west", "occupied": "true", "part": "foot" } },
    { "bedrock_states": { "color": 9, "direction": 1, "occupied_bit": 1, "head_piece_bit": 1 }, "java_id": "minecraft:cyan_bed", "java_states": { "facing": "west", "occupied": "true", "part": "head" } },
    { "bedrock_states": { "color": 9, "direction": 2, "occupied_bit": 0, "head_piece_bit": 0 }, "java_id": "minecraft:cyan_bed", "java_states": { "facing": "north", "occupied": "false", "part": "foot" } },
    { "bedrock_states": { "color": 9, "direction": 2, "occupied_bit": 0, "head_piece_bit": 1 }, "java_id": "minecraft:cyan_bed", "java_states": { "facing": "north", "occupied": "false", "part": "head" } },
    { "bedrock_states": { "color": 9, "direction": 2, "occupied_bit": 1, "head_piece_bit": 0 }, "java_id": "minecraft:cyan_bed", "java_states": { "facing": "north", "occupied": "true", "part": "foot" } },
    { "bedrock_states": { "color": 9, "direction": 2, "occupied_bit": 1, "head_piece_bit": 1 }, "java_id": "minecraft:cyan_bed", "java_states": { "facing": "north", "occupied": "true", "part": "head" } },
    { "bedrock_states": { "color": 9, "direction": 3, "occupied_bit": 0, "head_piece_bit": 0 }, "java_id": "minecraft:cyan_bed", "java_states": { "facing": "east", "occupied": "false", "part": "foot" } },
    { "bedrock_states": { "color": 9, "direction": 3, "occupied_bit": 0, "head_piece_bit": 1 }, "java_id": "minecraft:cyan_bed", "java_states": { "facing": "east", "occupied": "false", "part": "head" } },
    { "bedrock_states": { "color": 9, "direction": 3, "occupied_bit": 1, "head_piece_bit": 0 }, "java_id": "minecraft:cyan_bed", "java_states": { "facing": "east", "occupied": "true", "part": "foot" } },
    { "bedrock_states": { "color": 9, "direction": 3, "occupied_bit": 1, "head_piece_bit": 1 }, "java_id": "minecraft:cyan_bed", "java_states": { "facing": "east", "occupied": "true", "part": "head" } },
    // --- color 10: purple ---
    { "bedrock_states": { "color": 10, "direction": 0, "occupied_bit": 0, "head_piece_bit": 0 }, "java_id": "minecraft:purple_bed", "java_states": { "facing": "south", "occupied": "false", "part": "foot" } },
    { "bedrock_states": { "color": 10, "direction": 0, "occupied_bit": 0, "head_piece_bit": 1 }, "java_id": "minecraft:purple_bed", "java_states": { "facing": "south", "occupied": "false", "part": "head" } },
    { "bedrock_states": { "color": 10, "direction": 0, "occupied_bit": 1, "head_piece_bit": 0 }, "java_id": "minecraft:purple_bed", "java_states": { "facing": "south", "occupied": "true", "part": "foot" } },
    { "bedrock_states": { "color": 10, "direction": 0, "occupied_bit": 1, "head_piece_bit": 1 }, "java_id": "minecraft:purple_bed", "java_states": { "facing": "south", "occupied": "true", "part": "head" } },
    { "bedrock_states": { "color": 10, "direction": 1, "occupied_bit": 0, "head_piece_bit": 0 }, "java_id": "minecraft:purple_bed", "java_states": { "facing": "west", "occupied": "false", "part": "foot" } },
    { "bedrock_states": { "color": 10, "direction": 1, "occupied_bit": 0, "head_piece_bit": 1 }, "java_id": "minecraft:purple_bed", "java_states": { "facing": "west", "occupied": "false", "part": "head" } },
    { "bedrock_states": { "color": 10, "direction": 1, "occupied_bit": 1, "head_piece_bit": 0 }, "java_id": "minecraft:purple_bed", "java_states": { "facing": "west", "occupied": "true", "part": "foot" } },
    { "bedrock_states": { "color": 10, "direction": 1, "occupied_bit": 1, "head_piece_bit": 1 }, "java_id": "minecraft:purple_bed", "java_states": { "facing": "west", "occupied": "true", "part": "head" } },
    { "bedrock_states": { "color": 10, "direction": 2, "occupied_bit": 0, "head_piece_bit": 0 }, "java_id": "minecraft:purple_bed", "java_states": { "facing": "north", "occupied": "false", "part": "foot" } },
    { "bedrock_states": { "color": 10, "direction": 2, "occupied_bit": 0, "head_piece_bit": 1 }, "java_id": "minecraft:purple_bed", "java_states": { "facing": "north", "occupied": "false", "part": "head" } },
    { "bedrock_states": { "color": 10, "direction": 2, "occupied_bit": 1, "head_piece_bit": 0 }, "java_id": "minecraft:purple_bed", "java_states": { "facing": "north", "occupied": "true", "part": "foot" } },
    { "bedrock_states": { "color": 10, "direction": 2, "occupied_bit": 1, "head_piece_bit": 1 }, "java_id": "minecraft:purple_bed", "java_states": { "facing": "north", "occupied": "true", "part": "head" } },
    { "bedrock_states": { "color": 10, "direction": 3, "occupied_bit": 0, "head_piece_bit": 0 }, "java_id": "minecraft:purple_bed", "java_states": { "facing": "east", "occupied": "false", "part": "foot" } },
    { "bedrock_states": { "color": 10, "direction": 3, "occupied_bit": 0, "head_piece_bit": 1 }, "java_id": "minecraft:purple_bed", "java_states": { "facing": "east", "occupied": "false", "part": "head" } },
    { "bedrock_states": { "color": 10, "direction": 3, "occupied_bit": 1, "head_piece_bit": 0 }, "java_id": "minecraft:purple_bed", "java_states": { "facing": "east", "occupied": "true", "part": "foot" } },
    { "bedrock_states": { "color": 10, "direction": 3, "occupied_bit": 1, "head_piece_bit": 1 }, "java_id": "minecraft:purple_bed", "java_states": { "facing": "east", "occupied": "true", "part": "head" } },
    // --- color 11: blue ---
    { "bedrock_states": { "color": 11, "direction": 0, "occupied_bit": 0, "head_piece_bit": 0 }, "java_id": "minecraft:blue_bed", "java_states": { "facing": "south", "occupied": "false", "part": "foot" } },
    { "bedrock_states": { "color": 11, "direction": 0, "occupied_bit": 0, "head_piece_bit": 1 }, "java_id": "minecraft:blue_bed", "java_states": { "facing": "south", "occupied": "false", "part": "head" } },
    { "bedrock_states": { "color": 11, "direction": 0, "occupied_bit": 1, "head_piece_bit": 0 }, "java_id": "minecraft:blue_bed", "java_states": { "facing": "south", "occupied": "true", "part": "foot" } },
    { "bedrock_states": { "color": 11, "direction": 0, "occupied_bit": 1, "head_piece_bit": 1 }, "java_id": "minecraft:blue_bed", "java_states": { "facing": "south", "occupied": "true", "part": "head" } },
    { "bedrock_states": { "color": 11, "direction": 1, "occupied_bit": 0, "head_piece_bit": 0 }, "java_id": "minecraft:blue_bed", "java_states": { "facing": "west", "occupied": "false", "part": "foot" } },
    { "bedrock_states": { "color": 11, "direction": 1, "occupied_bit": 0, "head_piece_bit": 1 }, "java_id": "minecraft:blue_bed", "java_states": { "facing": "west", "occupied": "false", "part": "head" } },
    { "bedrock_states": { "color": 11, "direction": 1, "occupied_bit": 1, "head_piece_bit": 0 }, "java_id": "minecraft:blue_bed", "java_states": { "facing": "west", "occupied": "true", "part": "foot" } },
    { "bedrock_states": { "color": 11, "direction": 1, "occupied_bit": 1, "head_piece_bit": 1 }, "java_id": "minecraft:blue_bed", "java_states": { "facing": "west", "occupied": "true", "part": "head" } },
    { "bedrock_states": { "color": 11, "direction": 2, "occupied_bit": 0, "head_piece_bit": 0 }, "java_id": "minecraft:blue_bed", "java_states": { "facing": "north", "occupied": "false", "part": "foot" } },
    { "bedrock_states": { "color": 11, "direction": 2, "occupied_bit": 0, "head_piece_bit": 1 }, "java_id": "minecraft:blue_bed", "java_states": { "facing": "north", "occupied": "false", "part": "head" } },
    { "bedrock_states": { "color": 11, "direction": 2, "occupied_bit": 1, "head_piece_bit": 0 }, "java_id": "minecraft:blue_bed", "java_states": { "facing": "north", "occupied": "true", "part": "foot" } },
    { "bedrock_states": { "color": 11, "direction": 2, "occupied_bit": 1, "head_piece_bit": 1 }, "java_id": "minecraft:blue_bed", "java_states": { "facing": "north", "occupied": "true", "part": "head" } },
    { "bedrock_states": { "color": 11, "direction": 3, "occupied_bit": 0, "head_piece_bit": 0 }, "java_id": "minecraft:blue_bed", "java_states": { "facing": "east", "occupied": "false", "part": "foot" } },
    { "bedrock_states": { "color": 11, "direction": 3, "occupied_bit": 0, "head_piece_bit": 1 }, "java_id": "minecraft:blue_bed", "java_states": { "facing": "east", "occupied": "false", "part": "head" } },
    { "bedrock_states": { "color": 11, "direction": 3, "occupied_bit": 1, "head_piece_bit": 0 }, "java_id": "minecraft:blue_bed", "java_states": { "facing": "east", "occupied": "true", "part": "foot" } },
    { "bedrock_states": { "color": 11, "direction": 3, "occupied_bit": 1, "head_piece_bit": 1 }, "java_id": "minecraft:blue_bed", "java_states": { "facing": "east", "occupied": "true", "part": "head" } },
    // --- color 12: brown ---
    { "bedrock_states": { "color": 12, "direction": 0, "occupied_bit": 0, "head_piece_bit": 0 }, "java_id": "minecraft:brown_bed", "java_states": { "facing": "south", "occupied": "false", "part": "foot" } },
    { "bedrock_states": { "color": 12, "direction": 0, "occupied_bit": 0, "head_piece_bit": 1 }, "java_id": "minecraft:brown_bed", "java_states": { "facing": "south", "occupied": "false", "part": "head" } },
    { "bedrock_states": { "color": 12, "direction": 0, "occupied_bit": 1, "head_piece_bit": 0 }, "java_id": "minecraft:brown_bed", "java_states": { "facing": "south", "occupied": "true", "part": "foot" } },
    { "bedrock_states": { "color": 12, "direction": 0, "occupied_bit": 1, "head_piece_bit": 1 }, "java_id": "minecraft:brown_bed", "java_states": { "facing": "south", "occupied": "true", "part": "head" } },
    { "bedrock_states": { "color": 12, "direction": 1, "occupied_bit": 0, "head_piece_bit": 0 }, "java_id": "minecraft:brown_bed", "java_states": { "facing": "west", "occupied": "false", "part": "foot" } },
    { "bedrock_states": { "color": 12, "direction": 1, "occupied_bit": 0, "head_piece_bit": 1 }, "java_id": "minecraft:brown_bed", "java_states": { "facing": "west", "occupied": "false", "part": "head" } },
    { "bedrock_states": { "color": 12, "direction": 1, "occupied_bit": 1, "head_piece_bit": 0 }, "java_id": "minecraft:brown_bed", "java_states": { "facing": "west", "occupied": "true", "part": "foot" } },
    { "bedrock_states": { "color": 12, "direction": 1, "occupied_bit": 1, "head_piece_bit": 1 }, "java_id": "minecraft:brown_bed", "java_states": { "facing": "west", "occupied": "true", "part": "head" } },
    { "bedrock_states": { "color": 12, "direction": 2, "occupied_bit": 0, "head_piece_bit": 0 }, "java_id": "minecraft:brown_bed", "java_states": { "facing": "north", "occupied": "false", "part": "foot" } },
    { "bedrock_states": { "color": 12, "direction": 2, "occupied_bit": 0, "head_piece_bit": 1 }, "java_id": "minecraft:brown_bed", "java_states": { "facing": "north", "occupied": "false", "part": "head" } },
    { "bedrock_states": { "color": 12, "direction": 2, "occupied_bit": 1, "head_piece_bit": 0 }, "java_id": "minecraft:brown_bed", "java_states": { "facing": "north", "occupied": "true", "part": "foot" } },
    { "bedrock_states": { "color": 12, "direction": 2, "occupied_bit": 1, "head_piece_bit": 1 }, "java_id": "minecraft:brown_bed", "java_states": { "facing": "north", "occupied": "true", "part": "head" } },
    { "bedrock_states": { "color": 12, "direction": 3, "occupied_bit": 0, "head_piece_bit": 0 }, "java_id": "minecraft:brown_bed", "java_states": { "facing": "east", "occupied": "false", "part": "foot" } },
    { "bedrock_states": { "color": 12, "direction": 3, "occupied_bit": 0, "head_piece_bit": 1 }, "java_id": "minecraft:brown_bed", "java_states": { "facing": "east", "occupied": "false", "part": "head" } },
    { "bedrock_states": { "color": 12, "direction": 3, "occupied_bit": 1, "head_piece_bit": 0 }, "java_id": "minecraft:brown_bed", "java_states": { "facing": "east", "occupied": "true", "part": "foot" } },
    { "bedrock_states": { "color": 12, "direction": 3, "occupied_bit": 1, "head_piece_bit": 1 }, "java_id": "minecraft:brown_bed", "java_states": { "facing": "east", "occupied": "true", "part": "head" } },
    // --- color 13: green ---
    { "bedrock_states": { "color": 13, "direction": 0, "occupied_bit": 0, "head_piece_bit": 0 }, "java_id": "minecraft:green_bed", "java_states": { "facing": "south", "occupied": "false", "part": "foot" } },
    { "bedrock_states": { "color": 13, "direction": 0, "occupied_bit": 0, "head_piece_bit": 1 }, "java_id": "minecraft:green_bed", "java_states": { "facing": "south", "occupied": "false", "part": "head" } },
    { "bedrock_states": { "color": 13, "direction": 0, "occupied_bit": 1, "head_piece_bit": 0 }, "java_id": "minecraft:green_bed", "java_states": { "facing": "south", "occupied": "true", "part": "foot" } },
    { "bedrock_states": { "color": 13, "direction": 0, "occupied_bit": 1, "head_piece_bit": 1 }, "java_id": "minecraft:green_bed", "java_states": { "facing": "south", "occupied": "true", "part": "head" } },
    { "bedrock_states": { "color": 13, "direction": 1, "occupied_bit": 0, "head_piece_bit": 0 }, "java_id": "minecraft:green_bed", "java_states": { "facing": "west", "occupied": "false", "part": "foot" } },
    { "bedrock_states": { "color": 13, "direction": 1, "occupied_bit": 0, "head_piece_bit": 1 }, "java_id": "minecraft:green_bed", "java_states": { "facing": "west", "occupied": "false", "part": "head" } },
    { "bedrock_states": { "color": 13, "direction": 1, "occupied_bit": 1, "head_piece_bit": 0 }, "java_id": "minecraft:green_bed", "java_states": { "facing": "west", "occupied": "true", "part": "foot" } },
    { "bedrock_states": { "color": 13, "direction": 1, "occupied_bit": 1, "head_piece_bit": 1 }, "java_id": "minecraft:green_bed", "java_states": { "facing": "west", "occupied": "true", "part": "head" } },
    { "bedrock_states": { "color": 13, "direction": 2, "occupied_bit": 0, "head_piece_bit": 0 }, "java_id": "minecraft:green_bed", "java_states": { "facing": "north", "occupied": "false", "part": "foot" } },
    { "bedrock_states": { "color": 13, "direction": 2, "occupied_bit": 0, "head_piece_bit": 1 }, "java_id": "minecraft:green_bed", "java_states": { "facing": "north", "occupied": "false", "part": "head" } },
    { "bedrock_states": { "color": 13, "direction": 2, "occupied_bit": 1, "head_piece_bit": 0 }, "java_id": "minecraft:green_bed", "java_states": { "facing": "north", "occupied": "true", "part": "foot" } },
    { "bedrock_states": { "color": 13, "direction": 2, "occupied_bit": 1, "head_piece_bit": 1 }, "java_id": "minecraft:green_bed", "java_states": { "facing": "north", "occupied": "true", "part": "head" } },
    { "bedrock_states": { "color": 13, "direction": 3, "occupied_bit": 0, "head_piece_bit": 0 }, "java_id": "minecraft:green_bed", "java_states": { "facing": "east", "occupied": "false", "part": "foot" } },
    { "bedrock_states": { "color": 13, "direction": 3, "occupied_bit": 0, "head_piece_bit": 1 }, "java_id": "minecraft:green_bed", "java_states": { "facing": "east", "occupied": "false", "part": "head" } },
    { "bedrock_states": { "color": 13, "direction": 3, "occupied_bit": 1, "head_piece_bit": 0 }, "java_id": "minecraft:green_bed", "java_states": { "facing": "east", "occupied": "true", "part": "foot" } },
    { "bedrock_states": { "color": 13, "direction": 3, "occupied_bit": 1, "head_piece_bit": 1 }, "java_id": "minecraft:green_bed", "java_states": { "facing": "east", "occupied": "true", "part": "head" } },
    // --- color 14: red ---
    { "bedrock_states": { "color": 14, "direction": 0, "occupied_bit": 0, "head_piece_bit": 0 }, "java_id": "minecraft:red_bed", "java_states": { "facing": "south", "occupied": "false", "part": "foot" } },
    { "bedrock_states": { "color": 14, "direction": 0, "occupied_bit": 0, "head_piece_bit": 1 }, "java_id": "minecraft:red_bed", "java_states": { "facing": "south", "occupied": "false", "part": "head" } },
    { "bedrock_states": { "color": 14, "direction": 0, "occupied_bit": 1, "head_piece_bit": 0 }, "java_id": "minecraft:red_bed", "java_states": { "facing": "south", "occupied": "true", "part": "foot" } },
    { "bedrock_states": { "color": 14, "direction": 0, "occupied_bit": 1, "head_piece_bit": 1 }, "java_id": "minecraft:red_bed", "java_states": { "facing": "south", "occupied": "true", "part": "head" } },
    { "bedrock_states": { "color": 14, "direction": 1, "occupied_bit": 0, "head_piece_bit": 0 }, "java_id": "minecraft:red_bed", "java_states": { "facing": "west", "occupied": "false", "part": "foot" } },
    { "bedrock_states": { "color": 14, "direction": 1, "occupied_bit": 0, "head_piece_bit": 1 }, "java_id": "minecraft:red_bed", "java_states": { "facing": "west", "occupied": "false", "part": "head" } },
    { "bedrock_states": { "color": 14, "direction": 1, "occupied_bit": 1, "head_piece_bit": 0 }, "java_id": "minecraft:red_bed", "java_states": { "facing": "west", "occupied": "true", "part": "foot" } },
    { "bedrock_states": { "color": 14, "direction": 1, "occupied_bit": 1, "head_piece_bit": 1 }, "java_id": "minecraft:red_bed", "java_states": { "facing": "west", "occupied": "true", "part": "head" } },
    { "bedrock_states": { "color": 14, "direction": 2, "occupied_bit": 0, "head_piece_bit": 0 }, "java_id": "minecraft:red_bed", "java_states": { "facing": "north", "occupied": "false", "part": "foot" } },
    { "bedrock_states": { "color": 14, "direction": 2, "occupied_bit": 0, "head_piece_bit": 1 }, "java_id": "minecraft:red_bed", "java_states": { "facing": "north", "occupied": "false", "part": "head" } },
    { "bedrock_states": { "color": 14, "direction": 2, "occupied_bit": 1, "head_piece_bit": 0 }, "java_id": "minecraft:red_bed", "java_states": { "facing": "north", "occupied": "true", "part": "foot" } },
    { "bedrock_states": { "color": 14, "direction": 2, "occupied_bit": 1, "head_piece_bit": 1 }, "java_id": "minecraft:red_bed", "java_states": { "facing": "north", "occupied": "true", "part": "head" } },
    { "bedrock_states": { "color": 14, "direction": 3, "occupied_bit": 0, "head_piece_bit": 0 }, "java_id": "minecraft:red_bed", "java_states": { "facing": "east", "occupied": "false", "part": "foot" } },
    { "bedrock_states": { "color": 14, "direction": 3, "occupied_bit": 0, "head_piece_bit": 1 }, "java_id": "minecraft:red_bed", "java_states": { "facing": "east", "occupied": "false", "part": "head" } },
    { "bedrock_states": { "color": 14, "direction": 3, "occupied_bit": 1, "head_piece_bit": 0 }, "java_id": "minecraft:red_bed", "java_states": { "facing": "east", "occupied": "true", "part": "foot" } },
    { "bedrock_states": { "color": 14, "direction": 3, "occupied_bit": 1, "head_piece_bit": 1 }, "java_id": "minecraft:red_bed", "java_states": { "facing": "east", "occupied": "true", "part": "head" } },
    // --- color 15: black ---
    { "bedrock_states": { "color": 15, "direction": 0, "occupied_bit": 0, "head_piece_bit": 0 }, "java_id": "minecraft:black_bed", "java_states": { "facing": "south", "occupied": "false", "part": "foot" } },
    { "bedrock_states": { "color": 15, "direction": 0, "occupied_bit": 0, "head_piece_bit": 1 }, "java_id": "minecraft:black_bed", "java_states": { "facing": "south", "occupied": "false", "part": "head" } },
    { "bedrock_states": { "color": 15, "direction": 0, "occupied_bit": 1, "head_piece_bit": 0 }, "java_id": "minecraft:black_bed", "java_states": { "facing": "south", "occupied": "true", "part": "foot" } },
    { "bedrock_states": { "color": 15, "direction": 0, "occupied_bit": 1, "head_piece_bit": 1 }, "java_id": "minecraft:black_bed", "java_states": { "facing": "south", "occupied": "true", "part": "head" } },
    { "bedrock_states": { "color": 15, "direction": 1, "occupied_bit": 0, "head_piece_bit": 0 }, "java_id": "minecraft:black_bed", "java_states": { "facing": "west", "occupied": "false", "part": "foot" } },
    { "bedrock_states": { "color": 15, "direction": 1, "occupied_bit": 0, "head_piece_bit": 1 }, "java_id": "minecraft:black_bed", "java_states": { "facing": "west", "occupied": "false", "part": "head" } },
    { "bedrock_states": { "color": 15, "direction": 1, "occupied_bit": 1, "head_piece_bit": 0 }, "java_id": "minecraft:black_bed", "java_states": { "facing": "west", "occupied": "true", "part": "foot" } },
    { "bedrock_states": { "color": 15, "direction": 1, "occupied_bit": 1, "head_piece_bit": 1 }, "java_id": "minecraft:black_bed", "java_states": { "facing": "west", "occupied": "true", "part": "head" } },
    { "bedrock_states": { "color": 15, "direction": 2, "occupied_bit": 0, "head_piece_bit": 0 }, "java_id": "minecraft:black_bed", "java_states": { "facing": "north", "occupied": "false", "part": "foot" } },
    { "bedrock_states": { "color": 15, "direction": 2, "occupied_bit": 0, "head_piece_bit": 1 }, "java_id": "minecraft:black_bed", "java_states": { "facing": "north", "occupied": "false", "part": "head" } },
    { "bedrock_states": { "color": 15, "direction": 2, "occupied_bit": 1, "head_piece_bit": 0 }, "java_id": "minecraft:black_bed", "java_states": { "facing": "north", "occupied": "true", "part": "foot" } },
    { "bedrock_states": { "color": 15, "direction": 2, "occupied_bit": 1, "head_piece_bit": 1 }, "java_id": "minecraft:black_bed", "java_states": { "facing": "north", "occupied": "true", "part": "head" } },
    { "bedrock_states": { "color": 15, "direction": 3, "occupied_bit": 0, "head_piece_bit": 0 }, "java_id": "minecraft:black_bed", "java_states": { "facing": "east", "occupied": "false", "part": "foot" } },
    { "bedrock_states": { "color": 15, "direction": 3, "occupied_bit": 0, "head_piece_bit": 1 }, "java_id": "minecraft:black_bed", "java_states": { "facing": "east", "occupied": "false", "part": "head" } },
    { "bedrock_states": { "color": 15, "direction": 3, "occupied_bit": 1, "head_piece_bit": 0 }, "java_id": "minecraft:black_bed", "java_states": { "facing": "east", "occupied": "true", "part": "foot" } },
    { "bedrock_states": { "color": 15, "direction": 3, "occupied_bit": 1, "head_piece_bit": 1 }, "java_id": "minecraft:black_bed", "java_states": { "facing": "east", "occupied": "true", "part": "head" } },
  ],

};
